graphile: npx postgraphile --watch --owner-connection $WATCH_DATABASE_URL --enhance-graphiql --append-plugins @graphile-contrib/pg-simplify-inflector --schema app_public
migrate: npx graphile-migrate watch
